from pathlib import Path
import json,html,shutil
root=Path(__file__).resolve().parents[2]
qa=root/'ArtSource/FurnitureLibrary/Validation/FurnitureLibraryQA'
report=json.loads((qa/'Result.json').read_text(encoding='utf8'))
out=root/'CompanyGame/Docs/FurnitureLibrary';out.mkdir(parents=True,exist_ok=True)
shutil.copytree(qa/'Previews',out/'Previews',dirs_exist_ok=True)
cats={'Seating':'의자 · 소파','Surface':'테이블 · 책상','Storage/General':'일반 수납','Storage/Clothing':'의류 수납','Storage/Food':'음식 보관 · 진열','Storage/Books':'책장','Sleep':'침대','Lighting':'조명','Cooking':'주방 기기','WaterSource':'수도 · 욕실','Display':'컴퓨터 · TV','Music':'스피커','Decoration':'장식품','Fixtures/Doors':'문'}
cards=[]
for row in report['items']:
    cat=cats.get(row['category'],row['category'])
    target=(root/'CompanyGame'/row['prefabPath']).as_uri()
    text=' '.join([row['label'],row['id'],cat,row.get('note',''),row.get('placement','')])
    cards.append(f'''<article data-cat="{html.escape(row['category'])}" data-search="{html.escape(text.lower())}"><img loading="lazy" src="{row['preview']}" alt="{html.escape(row['label'])}"><div><small>{cat} · {'화이트우드' if row['reused'] else '다운로드'}</small><h2>{html.escape(row['label'])}</h2><code>{row['id']}</code><p>{html.escape(row.get('note','')) or '개별 프리팹 · 바닥 중심 원점'}</p><a href="{target}">프리팹 파일</a><details><summary>Unity 경로 · 분류</summary><p>{row['prefabPath']}</p><p>{row.get('functions','')} / {row.get('storage','')} / {row.get('placement','')}</p><p>출처: {html.escape(row['source'])}</p></details></div></article>''')
options=''.join(f'<option value="{c}">{cats.get(c,c)}</option>' for c in sorted({r['category'] for r in report['items']}))
doc='''<!doctype html><html lang="ko"><meta charset="utf-8"><title>가구 에셋 라이브러리</title><style>*{box-sizing:border-box}body{margin:0;background:#13191c;color:#e9e9e4;font:15px/1.55 system-ui}header{padding:40px 5vw 24px;background:#1d282d}h1{font-size:34px;margin:0}header p{color:#b8c6c4;max-width:1000px}.tools{display:flex;gap:12px;position:sticky;top:0;background:#1d282d;padding:15px 5vw;z-index:2}input,select{background:#10171b;color:white;border:1px solid #54716e;border-radius:8px;padding:12px;font:inherit}input{flex:1}.grid{padding:26px 5vw;display:grid;grid-template-columns:repeat(auto-fill,minmax(240px,1fr));gap:20px}article{background:#202b30;border:1px solid #364449;border-radius:12px;overflow:hidden}article img{width:100%;aspect-ratio:1;object-fit:contain;background:#292e33}article>div{padding:18px}small{color:#83c1ae}h2{font-size:19px;margin:8px 0}code{font-size:11px;color:#b9c6c9}article p{font-size:13px;color:#a6b8b9;overflow-wrap:anywhere;min-height:20px}a{color:#ade8cb}details{margin-top:12px;font-size:12px}footer{padding:30px 5vw;color:#c1bbaa}article[hidden]{display:none}</style><header><h1>가구 에셋 라이브러리</h1><p>87개 개별 프리팹 · Unity URP · 원본 보존<br>씬에 배치할 때 아래 Unity 경로의 프리팹을 드래그하세요. 기능은 분류 정보이며, 앉기·수납·조명 등의 게임 동작은 배치할 때 연결합니다.</p></header><div class="tools"><input id="search" placeholder="이름, 기능, 영문 ID로 검색"><select id="category"><option value="">전체 분류</option>OPTIONS</select><span id="count"></span></div><main class="grid">CARDS</main><footer>미포함: 공중전화기·금괴·베이커리 카운터·오락기계·화장실 표지판 ZIP은 실제 모델이 아닌 BlenderKit 설치 파일입니다.<br>sofa_company.fbx와 sofa_company2.fbx는 동일 파일이므로 하나로 정리했습니다. 차량·무기·캐릭터·건물·모션은 이번 가구 목록에 포함하지 않았습니다.</footer><script>const cards=[...document.querySelectorAll('article')];function filter(){let n=0;for(const c of cards){c.hidden=!(c.dataset.search.includes(search.value.toLowerCase())&&(!category.value||c.dataset.cat===category.value));if(!c.hidden)n++}count.textContent=n+'개'}search.oninput=category.onchange=filter;filter()</script></html>'''.replace('OPTIONS',options).replace('CARDS',''.join(cards))
(out/'Catalog.html').write_text(doc,encoding='utf8')
print('Catalog',len(report['items']),'validated',report['count'],'errors',report['errors'])
